# TODO. IN GENERAL INVESTIGATE WHAT IS A GOOD WAY TO SET UP THE PRECOMMITS
default_stages: [pre-commit]
repos:
  - repo: local
    hooks:
      #       - id: check-build-files
      #         name: check-build-files
      #         entry: bash -c "pants tailor --check update-build-files --check ::"
      #         language: system
      #         pass_filenames: false
      #         stages: [pre-commit]
      - id: check-code-format-and-style
        name: check-code-format-and-style
        entry: sh -c "pants lint ::"
        language: system
        pass_filenames: false
        #stages: [pre-commit]
# TODO. CHECK BUG THAT DOES NOT ALLOW TO PERFORM THIS TASK (MyPy problem)
# 16:25:31.27 [ERROR] Completed: Typecheck using MyPy - mypy - mypy failed (exit code 2).
# mnist/src/data.py: error: Source file found twice under different module names: "data" and "mnist.src.data"
# mnist/src/data.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
# mnist/src/data.py: note: Common resolutions include: a) adding `__init__.py` somewhere, b) using `--explicit-package-bases` or adjusting MYPYPATH
# Found 1 error in 1 file (errors prevented further checking)
# - id: check-typing
#   name: check-typing
#   entry: sh -c "pants --changed-since=main --changed-dependees=transitive check"
#   language: system
#   pass_filenames: false
#   stages: [pre-commit]

# - id: run-tests
#   name: run-tests
#   entry: sh -c "pants test ::"
#   language: system
#   pass_filenames: false
#   stages: [pre-commit]

# TODO. ADD PUSH COMMITS FOR THE DOCKER FILES
