stages:

  clean:
    cmd: >
      python src/clean.py
    deps:
    - src/clean.py
    - data/raw/
    params:
    - general.seed
    outs:
    - data/clean/

  featurize:
    cmd: >
      python src/featurize.py
    deps:
    - src/featurize.py
    - data/clean/
    params:
    - general.seed
    outs:
    - data/featurized/

  evaluate:
    cmd: >
      python src/evaluate.py
    deps:
    - src/evaluate.py
    - data/featurized/
    params:
    - general.seed
    outs:
    - data/predictions/
    - data/submissions/
    # metrics:
    # - scores.json:
    #     cache: false
    # plots:
    # - metric1.json:
    #     cache: false
