name: loanlosspredictiondvc
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - dvc
  - flake8
  - kaggle
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - python-dotenv>=0.5.1
  - scikit-learn
  - seaborn
